// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0CxsM5pLeCavC0cteZxN3XO8J0fO_Yc',
    appId: '1:917969859882:web:c0906b05e9c71aa0621a53',
    messagingSenderId: '917969859882',
    projectId: 'clothnear',
    authDomain: 'clothnear.firebaseapp.com',
    storageBucket: 'clothnear.firebasestorage.app',
    measurementId: 'G-R9BGBPMXJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3kTF3l5vvCz72zoz7-ccv3uuYyTq9iA',
    appId: '1:917969859882:android:c8c5fe0032151cfe621a53',
    messagingSenderId: '917969859882',
    projectId: 'clothnear',
    storageBucket: 'clothnear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYdAg3WvDbQl7oZIfaP9qk8Bgd6XMT9Q',
    appId: '1:917969859882:ios:8b1c42c6148f5d80621a53',
    messagingSenderId: '917969859882',
    projectId: 'clothnear',
    storageBucket: 'clothnear.firebasestorage.app',
    iosBundleId: 'com.example.clothnear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRYdAg3WvDbQl7oZIfaP9qk8Bgd6XMT9Q',
    appId: '1:917969859882:ios:8b1c42c6148f5d80621a53',
    messagingSenderId: '917969859882',
    projectId: 'clothnear',
    storageBucket: 'clothnear.firebasestorage.app',
    iosBundleId: 'com.example.clothnear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR0CxsM5pLeCavC0cteZxN3XO8J0fO_Yc',
    appId: '1:917969859882:web:6dced7bcbf7eae55621a53',
    messagingSenderId: '917969859882',
    projectId: 'clothnear',
    authDomain: 'clothnear.firebaseapp.com',
    storageBucket: 'clothnear.firebasestorage.app',
    measurementId: 'G-X60X79B2K1',
  );

}