#!/usr/bin/env python3
"""Writes lib/config/api_secrets.dart from GEMINI_API_KEY env (CI)."""
import os
import json
from pathlib import Path

key = os.environ.get("GEMINI_API_KEY", "").strip()
if not key:
    raise SystemExit("GEMINI_API_KEY environment variable is empty")

out = Path(__file__).resolve().parents[1] / "lib" / "config" / "api_secrets.dart"
out.write_text(
    f"""// GENERATED BY CI — DO NOT COMMIT REAL KEYS
abstract class ApiSecrets {{
  static const String geminiApiKey = {json.dumps(key)};
  static const String geminiModel = 'gemini-2.5-flash';
}}
""",
    encoding="utf-8",
)
print(f"Wrote {out} ({len(key)} char key)")
